-- Sân bay mẫu (BACKEND_SCHEMA §8.1).
INSERT INTO airports (code, name, city, country_code, timezone) VALUES
    ('HAN', 'Nội Bài',       'Hà Nội',          'VN', 'Asia/Ho_Chi_Minh'),
    ('SGN', 'Tân Sơn Nhất',  'TP. Hồ Chí Minh', 'VN', 'Asia/Ho_Chi_Minh'),
    ('DAD', 'Đà Nẵng',       'Đà Nẵng',         'VN', 'Asia/Ho_Chi_Minh'),
    ('CXR', 'Cam Ranh',      'Nha Trang',       'VN', 'Asia/Ho_Chi_Minh'),
    ('PQC', 'Phú Quốc',      'Phú Quốc',        'VN', 'Asia/Ho_Chi_Minh'),
    ('HPH', 'Cát Bi',        'Hải Phòng',       'VN', 'Asia/Ho_Chi_Minh'),
    ('VCA', 'Cần Thơ',       'Cần Thơ',         'VN', 'Asia/Ho_Chi_Minh'),
    ('HUI', 'Phú Bài',       'Huế',             'VN', 'Asia/Ho_Chi_Minh'),
    ('VII', 'Vinh',          'Vinh',            'VN', 'Asia/Ho_Chi_Minh'),
    ('DLI', 'Liên Khương',   'Đà Lạt',          'VN', 'Asia/Ho_Chi_Minh'),
    ('UIH', 'Phù Cát',       'Quy Nhơn',        'VN', 'Asia/Ho_Chi_Minh'),
    ('BMV', 'Buôn Ma Thuột', 'Buôn Ma Thuột',   'VN', 'Asia/Ho_Chi_Minh'),
    ('THD', 'Thọ Xuân',      'Thanh Hoá',       'VN', 'Asia/Ho_Chi_Minh'),
    ('VDO', 'Vân Đồn',       'Quảng Ninh',      'VN', 'Asia/Ho_Chi_Minh'),
    ('PXU', 'Pleiku',        'Pleiku',          'VN', 'Asia/Ho_Chi_Minh'),
    ('VCS', 'Côn Đảo',       'Côn Đảo',         'VN', 'Asia/Ho_Chi_Minh'),
    ('TBB', 'Tuy Hoà',       'Tuy Hoà',         'VN', 'Asia/Ho_Chi_Minh'),
    ('VKG', 'Rạch Giá',      'Rạch Giá',        'VN', 'Asia/Ho_Chi_Minh'),
    ('CAH', 'Cà Mau',        'Cà Mau',          'VN', 'Asia/Ho_Chi_Minh'),
    ('DIN', 'Điện Biên Phủ', 'Điện Biên Phủ',   'VN', 'Asia/Ho_Chi_Minh'),
    ('VDH', 'Đồng Hới',      'Đồng Hới',        'VN', 'Asia/Ho_Chi_Minh'),
    ('BKK', 'Suvarnabhumi',               'Bangkok',      'TH', 'Asia/Bangkok'),
    ('SIN', 'Changi',                     'Singapore',    'SG', 'Asia/Singapore'),
    ('KUL', 'Kuala Lumpur International', 'Kuala Lumpur', 'MY', 'Asia/Kuala_Lumpur'),
    ('ICN', 'Incheon',                    'Seoul',        'KR', 'Asia/Seoul'),
    ('NRT', 'Narita',                     'Tokyo',        'JP', 'Asia/Tokyo'),
    ('HKG', 'Hong Kong International',    'Hong Kong',    'HK', 'Asia/Hong_Kong'),
    ('TPE', 'Taoyuan',                    'Đài Bắc',      'TW', 'Asia/Taipei'),
    ('CAN', 'Bạch Vân',                   'Quảng Châu',   'CN', 'Asia/Shanghai');
